// Generated by CoffeeScript 2.0.1
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.get('/', function(request, response) {
    return response.send("Hello, world.");
  });

  app.listen(3000);

}).call(this);
