// Generated by CoffeeScript 2.0.1
(function() {
  var app, express, mongoose, port, uri;

  mongoose = require('mongoose');

  express = require('express');

  app = express();

  uri = 'mongodb://mongo:27017';

  port = process.env.PORT || 3000;

  mongoose.connect(uri, function(error, response) {
    if (error) {
      return console.log(`An error occured while connecting to ${uri}: ${error}`);
    } else {
      return console.log(`Successfully connected to ${uri}.`);
    }
  });

  app.set('view engine', 'pug');

  app.get('/', function(request, response) {
    return response.render('index', {
      title: 'Some title',
      message: 'Some message.'
    });
  });

  app.listen(port);

}).call(this);
